Ispit.ToDo/Models/ErrorViewModel.cs
namespace Ispit.ToDo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ispit.ToDo/Models/TodoTask.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ispit.ToDo.Models
{
    public class TodoTask
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [Required]
        public bool Status { get; set; }

        [ForeignKey("TodolistId")]
        public Todolist Todolist { get; set; }
        public int TodolistId { get; set; }
        
    }
}

Ispit.ToDo/Models/Todolist.cs
using Ispit.ToDo.Data;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ispit.ToDo.Models
{
    public class Todolist
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [ForeignKey("UserId")]
        public ApplicationUser User { get; set; }
        public string? UserId { get; set; }

    }
}

Ispit.ToDo/Areas/User/Controllers/TodolistController.cs
using Ispit.ToDo.Data;
using Ispit.ToDo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Ispit.ToDo.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class TodolistController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public TodolistController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: TodolistController
        public ActionResult Index()
        {

            return View(_context.Todolists.ToList());
        }

        // GET: TodolistController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TodolistController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TodolistController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Todolist list)
        {
            try
            {
                list.User = await _userManager.GetUserAsync(User);

                _context.Todolists.Add(list);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TodolistController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TodolistController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TodolistController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TodolistController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Ispit.ToDo/Areas/User/Controllers/TodotaskController.cs
using Ispit.ToDo.Data;
using Ispit.ToDo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Ispit.ToDo.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class TodotaskController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TodotaskController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: TodotaskController
        public ActionResult Index(int todoListId)
        {
            return View(_context.TodoTasks.Where(task => task.TodolistId == todoListId).ToList());
        }

        // GET: TodotaskController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TodotaskController/Create
        public ActionResult Create(int todoListId)
        {
            ViewBag.TodolistId = todoListId;
            return View();
        }

        // POST: TodotaskController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TodoTask task)
        {
            try
            {
                _context.TodoTasks.Add(task);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index), task.TodolistId);
            }
            catch
            {
                return View();
            }
        }

        // GET: TodotaskController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TodotaskController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TodotaskController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TodotaskController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Ispit.ToDo/Areas/User/Controllers/UserController.cs
using Ispit.ToDo.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Ispit.ToDo.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            
            return View(_context.Todolists.ToList());
        }
    }
}

Ispit.ToDo/Controllers/HomeController.cs
using Ispit.ToDo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Ispit.ToDo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ispit.ToDo/Areas/User/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ispit.ToDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ispit.ToDo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ispit.ToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="User" asp-controller="User" asp-action="Index">User profile</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ispit.ToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Ispit.ToDo/Areas/User/Views/Todolist/Create.cshtml
@model Ispit.ToDo.Models.Todolist

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Todolist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ispit.ToDo/Areas/User/Views/Todolist/Index.cshtml
@model IEnumerable<Ispit.ToDo.Models.Todolist>


@{
    ViewData["Title"] = "Index";
}

<h1>Tasks list</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                <a asp-controller="Todotask" asp-action="Create" asp-route-todoListId="@item.Id">Create new task</a>
            </td>
        </tr>
}
    </tbody>
</table>

Ispit.ToDo/Areas/User/Views/Todotask/Create.cshtml
@model Ispit.ToDo.Models.TodoTask

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TodoTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                </label>
            </div>
            <input asp-for="TodolistId" class ="form-control" type="hidden" asp-items="ViewBag.TodolistId" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ispit.ToDo/Areas/User/Views/Todotask/Index.cshtml
@model IEnumerable<Ispit.ToDo.Models.TodoTask>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Ispit.ToDo/Areas/User/Views/User/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Ispit.ToDo.Data
@model IEnumerable<Ispit.ToDo.Models.Todolist>

@inject UserManager<ApplicationUser> UserManager

@{
    ApplicationUser user = await UserManager.GetUserAsync(User);
}


<div>
    <h4>User info</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => user.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => user.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => user.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => user.LastName)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => user.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => user.Address)
        </dd>
    </dl>
</div>

<h1>Tasks list</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) 
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                <a asp-controller="Todotask" asp-action="Create" asp-route-todoListId="@item.Id">Create new task</a>
            </td>
        </tr>
}
    </tbody>
</table>

<a asp-area="User" asp-controller="Todolist" asp-action="Create">Create new todo list</a> 

Ispit.ToDo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Ispit.ToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ispit.ToDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ispit.ToDo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ispit.ToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="User" asp-controller="User" asp-action="Index">User profile</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ispit.ToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>